[project]
name = "fi-utils-project"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = []

[tools.setuptools.package.find]
where=["."]
exclude=["experiments*","test*"]